[package]
name = "kestrel-runtime-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ahash = { workspace = true }
wasmtime = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
regex = { workspace = true }
glob = { workspace = true }
parking_lot = "0.12"
kestrel-schema = { path = "../kestrel-schema" }
kestrel-event = { path = "../kestrel-event" }


[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
wat = { workspace = true }
kestrel-eql = { path = "../kestrel-eql" }
